# Generated by Django 5.0.1 on 2024-07-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='cover-picture/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='profile-picture/'),
        ),
    ]
