# Generated by Django 5.0.1 on 2024-09-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_alter_user_cover_picture_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Headmaster', 'Headmaster'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], max_length=100),
        ),
    ]
