# Generated by Django 5.0.1 on 2025-02-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
