# Generated by Django 5.0.1 on 2025-02-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0017_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
