# Generated by Django 5.0.1 on 2025-02-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0018_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
