# Generated by Django 5.0.1 on 2025-03-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_role_campus_role_school_user_campus_user_school_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='role',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='role',
            name='school',
        ),
    ]
