# Generated by Django 5.0.1 on 2025-03-07 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('student_performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_assessments', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_assessments', to='school.school'),
        ),
        migrations.AlterField(
            model_name='assessmentname',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_assessment_names', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='assessmentname',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_assessment_names', to='school.school'),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_class_enrollment', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_class_enrollment', to='school.school'),
        ),
        migrations.AlterField(
            model_name='historicalassessmentresult',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_historical_assessment_result', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='historicalassessmentresult',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_historical_assessment_result', to='school.school'),
        ),
        migrations.AlterField(
            model_name='historicalclassenrollment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_historical_class_enrollment', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='historicalclassenrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_historical_class_enrollment', to='school.school'),
        ),
        migrations.AlterField(
            model_name='processedmarks',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_processed_marks', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='processedmarks',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_processed_marks', to='school.school'),
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_student_parent_relation', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_student_parent_relation', to='school.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_subjects', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='school.school'),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_subject_performance', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_performance', to='school.school'),
        ),
        migrations.AlterField(
            model_name='teacherassignmenthistory',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_teacher_assignment_history', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='teacherassignmenthistory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_teacher_assignment_history', to='school.school'),
        ),
        migrations.AlterField(
            model_name='teacherlevelclass',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_teacher_level_class', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='teacherlevelclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_teacher_level_class', to='school.school'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_terms', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoo_terms', to='school.school'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_timetables', to='school.campus'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_timetables', to='school.school'),
        ),
    ]
