# Generated by Django 4.2.5 on 2024-02-16 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='term',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherlevelclass',
            name='subjects_taught',
            field=models.ManyToManyField(related_name='teacher_level_classes', to='student_performance.subject'),
        ),
        migrations.CreateModel(
            name='HistoricalClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.student')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.assessment')),
                ('historical_class_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.historicalclassenrollment')),
            ],
        ),
    ]
