# Generated by Django 5.0.1 on 2025-03-20 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('school', '0001_initial'),
        ('student_performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentname',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_assessment_names', to='school.campus'),
        ),
        migrations.AddField(
            model_name='assessmentname',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_assessment_names', to='school.school'),
        ),
        migrations.AddField(
            model_name='assessmentname',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_assessment_names', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='student_performance.assessmentname'),
        ),
        migrations.AddField(
            model_name='class',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_classes', to='school.campus'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='school.school'),
        ),
        migrations.AddField(
            model_name='assessmentname',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_names', to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.academicyear'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_class_enrollment', to='school.campus'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_class_enrollment', to='school.school'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_class_subjects', to='school.campus'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_assigned', to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_class_subjects', to='school.school'),
        ),
        migrations.AddField(
            model_name='historicalassessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.assessment'),
        ),
        migrations.AddField(
            model_name='historicalassessmentresult',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_historical_assessment_result', to='school.campus'),
        ),
        migrations.AddField(
            model_name='historicalassessmentresult',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_historical_assessment_result', to='school.school'),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.academicyear'),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_historical_class_enrollment', to='school.campus'),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='class_enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_historical_class_enrollment', to='school.school'),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='historical_class_enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalassessmentresult',
            name='historical_class_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.historicalclassenrollment'),
        ),
        migrations.AddField(
            model_name='level',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_levels', to='school.campus'),
        ),
        migrations.AddField(
            model_name='level',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_levels', to='school.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='student_performance.level'),
        ),
        migrations.AddField(
            model_name='processedmarks',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_processed_marks', to='school.campus'),
        ),
        migrations.AddField(
            model_name='processedmarks',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='processedmarks',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_processed_marks', to='school.school'),
        ),
        migrations.AddField(
            model_name='processedmarks',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentparentrelation',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_student_parent_relation', to='school.campus'),
        ),
        migrations.AddField(
            model_name='studentparentrelation',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentparentrelation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_student_parent_relation', to='school.school'),
        ),
        migrations.AddField(
            model_name='studentparentrelation',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_subjects', to='school.campus'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='school.school'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_assigned', to='student_performance.subject'),
        ),
        migrations.AddField(
            model_name='assessmentname',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_names', to='student_performance.subject'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.subject'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_subject_performance', to='school.campus'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_performance', to='school.school'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignmenthistory',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_teacher_assignment_history', to='school.campus'),
        ),
        migrations.AddField(
            model_name='teacherassignmenthistory',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='teacherassignmenthistory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_teacher_assignment_history', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherassignmenthistory',
            name='subjects_taught',
            field=models.ManyToManyField(to='student_performance.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignmenthistory',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherlevelclass',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_teacher_level_class', to='school.campus'),
        ),
        migrations.AddField(
            model_name='teacherlevelclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher_level_classes', to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='teacherlevelclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_teacher_level_class', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherlevelclass',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='teacher_level_classes', to='student_performance.subject'),
        ),
        migrations.AddField(
            model_name='teacherlevelclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_level_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terms',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_terms', to='school.campus'),
        ),
        migrations.AddField(
            model_name='terms',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoo_terms', to='school.school'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_performance.terms'),
        ),
        migrations.AddField(
            model_name='processedmarks',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_performance.terms'),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.terms'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.terms'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.terms'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_timetables', to='school.campus'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='student_performance.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_timetables', to='school.school'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studentparentrelation',
            constraint=models.UniqueConstraint(fields=('student', 'parent'), name='unique_parent_student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentparentrelation',
            unique_together={('student', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_id', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentname',
            unique_together={('name', 'class_id', 'subject', 'teacher')},
        ),
    ]
