# Generated by Django 5.0.1 on 2025-03-05 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('student_performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='school.campus'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='school.school'),
        ),
        migrations.AddField(
            model_name='assessmentname',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_names', to='school.campus'),
        ),
        migrations.AddField(
            model_name='assessmentname',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_names', to='school.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_classes', to='school.campus'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='school.school'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollment', to='school.campus'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollment', to='school.school'),
        ),
        migrations.AddField(
            model_name='historicalassessmentresult',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_assessment_result', to='school.campus'),
        ),
        migrations.AddField(
            model_name='historicalassessmentresult',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_assessment_result', to='school.school'),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_class_enrollment', to='school.campus'),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_class_enrollment', to='school.school'),
        ),
        migrations.AddField(
            model_name='processedmarks',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_marks', to='school.campus'),
        ),
        migrations.AddField(
            model_name='processedmarks',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_marks', to='school.school'),
        ),
        migrations.AddField(
            model_name='studentparentrelation',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_parent_relation', to='school.campus'),
        ),
        migrations.AddField(
            model_name='studentparentrelation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_parent_relation', to='school.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.campus'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.school'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_performance', to='school.campus'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_performance', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherassignmenthistory',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment_history', to='school.campus'),
        ),
        migrations.AddField(
            model_name='teacherassignmenthistory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment_history', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherlevelclass',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_level_class', to='school.campus'),
        ),
        migrations.AddField(
            model_name='teacherlevelclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_level_class', to='school.school'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.campus'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.school'),
        ),
    ]
