# Generated by Django 5.0.1 on 2025-03-08 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0002_alter_assessment_campus_alter_assessment_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedmarks',
            old_name='term_id',
            new_name='term',
        ),
        migrations.RenameField(
            model_name='subjectperformance',
            old_name='term_id',
            new_name='term',
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.terms'),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.terms'),
        ),
    ]
