# Generated by Django 5.0.1 on 2025-04-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='level_type',
        ),
    ]
