# Generated by Django 5.0.1 on 2024-03-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0003_alter_class_level_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='class_associated',
            new_name='class_id',
        ),
    ]
