# Generated by Django 5.0.1 on 2025-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0003_remove_class_level_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
