# Generated by Django 5.0.1 on 2025-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0003_rename_term_id_processedmarks_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
