# Generated by Django 5.0.1 on 2024-03-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0005_remove_teacherlevelclass_level_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherlevelclass',
            old_name='class_name',
            new_name='class_id',
        ),
    ]
