# Generated by Django 5.0.1 on 2025-03-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0005_processedmarks_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='assessment_name_id',
            new_name='assessment_name',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_id',
        ),
    ]
