# Generated by Django 5.0.1 on 2024-03-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0007_rename_class_enrolled_student_class_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
