# Generated by Django 5.0.1 on 2024-04-03 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0010_remove_assessment_student_assessment_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.student'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessment', to=settings.AUTH_USER_MODEL),
        ),
    ]
