# Generated by Django 5.0.1 on 2024-04-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0011_alter_assessment_student_id_alter_assessment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.class'),
        ),
    ]
