# Generated by Django 5.0.1 on 2024-04-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0013_alter_assessment_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='term',
            new_name='semester',
        ),
    ]
