# Generated by Django 5.0.1 on 2024-06-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0014_rename_term_assessment_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='classenrollment',
            name='status',
            field=models.CharField(choices=[('existing', 'Existing'), ('promoted', 'Promoted')], default='existing', max_length=10),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
