# Generated by Django 5.0.1 on 2024-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0015_classenrollment_status_alter_assessment_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalclassenrollment',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='historicalclassenrollment',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
