# Generated by Django 5.0.1 on 2024-06-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0018_student_gender_student_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
    ]
