# Generated by Django 5.0.1 on 2024-06-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0020_student_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
