# Generated by Django 5.0.1 on 2024-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0022_alter_student_options_alter_classenrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_profile_pic',
            field=models.ImageField(null=True, upload_to='student_profile_pic/'),
        ),
    ]
