# Generated by Django 5.0.1 on 2024-07-27 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0023_alter_student_student_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(limit_choices_to={'user_type': 'Parent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentparentrelation',
            constraint=models.UniqueConstraint(fields=('student', 'parent'), name='unique_parent_student'),
        ),
        migrations.AddConstraint(
            model_name='studentparentrelation',
            constraint=models.UniqueConstraint(fields=('student',), name='max_two_parents'),
        ),
        migrations.AlterUniqueTogether(
            name='studentparentrelation',
            unique_together={('student', 'parent')},
        ),
    ]
