# Generated by Django 5.0.1 on 2024-08-18 15:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0024_studentparentrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('1st Semester', 'Semester 1'), ('2nd Semester', 'Semester 2')], max_length=50)),
                ('average_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.subject')),
            ],
        ),
    ]
