# Generated by Django 5.0.1 on 2024-09-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0026_processedmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedmarks',
            name='position',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
