# Generated by Django 5.0.1 on 2024-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0027_processedmarks_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlevelclass',
            name='is_main_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
