# Generated by Django 5.0.1 on 2024-11-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0030_alter_timetable_subject_alter_timetable_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_performance.class'),
        ),
    ]
