# Generated by Django 5.0.1 on 2025-02-11 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0032_teacherassignmenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentparentrelation',
            name='max_two_parents',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='student_id',
        ),
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalclassenrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='historical_class_enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processedmarks',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentparentrelation',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
