# Generated by Django 5.0.1 on 2025-02-22 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_academicyear_is_active'),
        ('student_performance', '0033_remove_studentparentrelation_max_two_parents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.academicyear'),
        ),
        migrations.AlterField(
            model_name='historicalclassenrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.academicyear'),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.academicyear'),
        ),
    ]
