# Generated by Django 5.0.1 on 2025-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0034_alter_classenrollment_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlevelclass',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='teacher_level_classes', to='student_performance.subject'),
        ),
    ]
