# Generated by Django 5.0.1 on 2025-03-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0035_alter_teacherlevelclass_subjects_taught'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
