# Generated by Django 5.0.1 on 2025-03-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0037_assessmentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentname',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_names', to='student_performance.class'),
        ),
        migrations.AlterField(
            model_name='assessmentname',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_names', to='student_performance.subject'),
        ),
    ]
